#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

FILE="vendor/docker/image.tar"

if [[ -e ${FILE} ]]; then
  docker load -i ${FILE}
else
  mkdir -p $(dirname ${FILE})
  docker build -t tmp-image .
  docker save tmp-image > ${FILE}
fi

