#!/bin/bash

docker run metrics \
  --env="AWS_ACCESS_KEY=${AWS_ACCESS_KEY}" \
  --env="AWS_SECRET_KEY=${AWS_SECRET_KEY}" \
  --env="AWS_SIMPLEDB_NAME=${AWS_SIMPLEDB_NAME}" \
  /metrics/bin/collect_metrics.py
